// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const.java
// Do not modify

package com.ltln.modules.openflow.core.protocol;


import com.ltln.modules.openflow.core.exceptions.*;
import com.ltln.modules.openflow.core.protocol.*;
import com.ltln.modules.openflow.core.protocol.action.*;
import com.ltln.modules.openflow.core.protocol.actionid.*;
import com.ltln.modules.openflow.core.protocol.bsntlv.*;
import com.ltln.modules.openflow.core.protocol.errormsg.*;
import com.ltln.modules.openflow.core.protocol.instruction.*;
import com.ltln.modules.openflow.core.protocol.instructionid.*;
import com.ltln.modules.openflow.core.protocol.match.*;
import com.ltln.modules.openflow.core.protocol.meterband.*;
import com.ltln.modules.openflow.core.protocol.oxm.*;
import com.ltln.modules.openflow.core.protocol.queueprop.*;
import com.ltln.modules.openflow.core.types.*;
import com.ltln.modules.openflow.core.util.*;

public enum OFBadRequestCode {
     BAD_VERSION,
     BAD_TYPE,
     BAD_STAT,
     BAD_EXPERIMENTER,
     BAD_SUBTYPE,
     EPERM,
     BAD_LEN,
     BUFFER_EMPTY,
     BUFFER_UNKNOWN,
     BAD_TABLE_ID,
     BAD_EXPERIMENTER_TYPE,
     IS_SLAVE,
     BAD_PORT,
     BAD_PACKET,
     MULTIPART_BUFFER_OVERFLOW,
     MULTIPART_REQUEST_TIMEOUT,
     MULTIPART_REPLY_TIMEOUT;
}
