// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const.java
// Do not modify

package com.ltln.modules.openflow.core.protocol;


import com.ltln.modules.openflow.core.exceptions.*;
import com.ltln.modules.openflow.core.protocol.*;
import com.ltln.modules.openflow.core.protocol.action.*;
import com.ltln.modules.openflow.core.protocol.actionid.*;
import com.ltln.modules.openflow.core.protocol.bsntlv.*;
import com.ltln.modules.openflow.core.protocol.errormsg.*;
import com.ltln.modules.openflow.core.protocol.instruction.*;
import com.ltln.modules.openflow.core.protocol.instructionid.*;
import com.ltln.modules.openflow.core.protocol.match.*;
import com.ltln.modules.openflow.core.protocol.meterband.*;
import com.ltln.modules.openflow.core.protocol.oxm.*;
import com.ltln.modules.openflow.core.protocol.queueprop.*;
import com.ltln.modules.openflow.core.types.*;
import com.ltln.modules.openflow.core.util.*;

public enum OFBsnPktinFlag {
     BSN_PKTIN_FLAG_PDU,
     BSN_PKTIN_FLAG_NEW_HOST,
     BSN_PKTIN_FLAG_STATION_MOVE,
     BSN_PKTIN_FLAG_ARP,
     BSN_PKTIN_FLAG_DHCP,
     BSN_PKTIN_FLAG_L2_CPU,
     BSN_PKTIN_FLAG_DEBUG,
     BSN_PKTIN_FLAG_TTL_EXPIRED,
     BSN_PKTIN_FLAG_L3_MISS,
     BSN_PKTIN_FLAG_L3_CPU,
     BSN_PKTIN_FLAG_INGRESS_ACL,
     BSN_PKTIN_FLAG_SFLOW,
     BSN_PKTIN_FLAG_ARP_CACHE,
     BSN_PKTIN_FLAG_ARP_TARGET,
     BSN_PKTIN_FLAG_IGMP,
     BSN_PKTIN_FLAG_PIM,
     BSN_PKTIN_FLAG_VXLAN_SIP_MISS,
     BSN_PKTIN_FLAG_MC_RESERVED;
}
