// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template of_factories.java
// Do not modify

package com.ltln.modules.openflow.core.protocol;


import com.ltln.modules.openflow.core.exceptions.*;
import com.ltln.modules.openflow.core.protocol.*;
import com.ltln.modules.openflow.core.protocol.action.*;
import com.ltln.modules.openflow.core.protocol.actionid.*;
import com.ltln.modules.openflow.core.protocol.bsntlv.*;
import com.ltln.modules.openflow.core.protocol.errormsg.*;
import com.ltln.modules.openflow.core.protocol.instruction.*;
import com.ltln.modules.openflow.core.protocol.instructionid.*;
import com.ltln.modules.openflow.core.protocol.match.*;
import com.ltln.modules.openflow.core.protocol.meterband.*;
import com.ltln.modules.openflow.core.protocol.oxm.*;
import com.ltln.modules.openflow.core.protocol.queueprop.*;
import com.ltln.modules.openflow.core.types.*;
import com.ltln.modules.openflow.core.util.*;

import io.netty.buffer.ByteBuf;

public final class OFFactories {

    private static final GenericReader GENERIC_READER = new GenericReader();

    public static OFFactory getFactory(OFVersion version) {
        switch(version) {
            case OF_10:
                return com.ltln.modules.openflow.core.protocol.ver10.OFFactoryVer10.INSTANCE;
            case OF_11:
                return com.ltln.modules.openflow.core.protocol.ver11.OFFactoryVer11.INSTANCE;
            case OF_12:
                return com.ltln.modules.openflow.core.protocol.ver12.OFFactoryVer12.INSTANCE;
            case OF_13:
                return com.ltln.modules.openflow.core.protocol.ver13.OFFactoryVer13.INSTANCE;
            case OF_14:
                return com.ltln.modules.openflow.core.protocol.ver14.OFFactoryVer14.INSTANCE;
            default:
                throw new IllegalArgumentException("Unknown version: "+version);
            }
    }

    private static class GenericReader implements OFMessageReader<OFMessage> {
        public OFMessage readFrom(ByteBuf bb) throws OFParseError {
            if(!bb.isReadable())
                return null;
            short wireVersion = U8.f(bb.getByte(bb.readerIndex()));
            OFFactory factory;
            switch (wireVersion) {
            case 1:
                factory = com.ltln.modules.openflow.core.protocol.ver10.OFFactoryVer10.INSTANCE;
                break;
            case 2:
                factory = com.ltln.modules.openflow.core.protocol.ver11.OFFactoryVer11.INSTANCE;
                break;
            case 3:
                factory = com.ltln.modules.openflow.core.protocol.ver12.OFFactoryVer12.INSTANCE;
                break;
            case 4:
                factory = com.ltln.modules.openflow.core.protocol.ver13.OFFactoryVer13.INSTANCE;
                break;
            case 5:
                factory = com.ltln.modules.openflow.core.protocol.ver14.OFFactoryVer14.INSTANCE;
                break;
            default:
                throw new IllegalArgumentException("Unknown wire version: " + wireVersion);
            }
            return factory.getReader().readFrom(bb);
        }
    }

    public static OFMessageReader<OFMessage> getGenericReader() {
        return GENERIC_READER;
    }
}
