// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template const.java
// Do not modify

package com.ltln.modules.openflow.core.protocol;


import com.ltln.modules.openflow.core.exceptions.*;
import com.ltln.modules.openflow.core.protocol.*;
import com.ltln.modules.openflow.core.protocol.action.*;
import com.ltln.modules.openflow.core.protocol.actionid.*;
import com.ltln.modules.openflow.core.protocol.bsntlv.*;
import com.ltln.modules.openflow.core.protocol.errormsg.*;
import com.ltln.modules.openflow.core.protocol.instruction.*;
import com.ltln.modules.openflow.core.protocol.instructionid.*;
import com.ltln.modules.openflow.core.protocol.match.*;
import com.ltln.modules.openflow.core.protocol.meterband.*;
import com.ltln.modules.openflow.core.protocol.oxm.*;
import com.ltln.modules.openflow.core.protocol.queueprop.*;
import com.ltln.modules.openflow.core.types.*;
import com.ltln.modules.openflow.core.util.*;

public enum OFPacketInReason {
     NO_MATCH,
     ACTION,
     INVALID_TTL,
     BSN_NEW_HOST,
     BSN_STATION_MOVE,
     BSN_BAD_VLAN,
     BSN_DESTINATION_LOOKUP_FAILURE,
     BSN_NO_ROUTE,
     BSN_ICMP_ECHO_REQUEST,
     BSN_DEST_NETWORK_UNREACHABLE,
     BSN_DEST_HOST_UNREACHABLE,
     BSN_DEST_PORT_UNREACHABLE,
     BSN_FRAGMENTATION_REQUIRED,
     BSN_ARP,
     BSN_DHCP,
     BSN_DEBUG,
     BSN_PACKET_OF_DEATH,
     ACTION_SET,
     GROUP,
     PACKET_OUT;
}
