// Copyright (c) 2008 The Board of Trustees of The Leland Stanford Junior University
// Copyright (c) 2011, 2012 Open Networking Foundation
// Copyright (c) 2012, 2013 Big Switch Networks, Inc.
// This library was generated by the LoxiGen Compiler.
// See the file LICENSE.txt which should have been included in the source distribution

// Automatically generated by LOXI from template of_factory_interface.java
// Do not modify

package com.ltln.modules.openflow.core.protocol.errormsg;


import com.ltln.modules.openflow.core.exceptions.*;
import com.ltln.modules.openflow.core.protocol.*;
import com.ltln.modules.openflow.core.protocol.action.*;
import com.ltln.modules.openflow.core.protocol.actionid.*;
import com.ltln.modules.openflow.core.protocol.bsntlv.*;
import com.ltln.modules.openflow.core.protocol.errormsg.*;
import com.ltln.modules.openflow.core.protocol.instruction.*;
import com.ltln.modules.openflow.core.protocol.instructionid.*;
import com.ltln.modules.openflow.core.protocol.match.*;
import com.ltln.modules.openflow.core.protocol.meterband.*;
import com.ltln.modules.openflow.core.protocol.oxm.*;
import com.ltln.modules.openflow.core.protocol.queueprop.*;
import com.ltln.modules.openflow.core.types.*;
import com.ltln.modules.openflow.core.util.*;

public interface OFErrorMsgs extends XidGenerator {
    // Subfactories

    OFBadActionErrorMsg.Builder buildBadActionErrorMsg();
    OFBadRequestErrorMsg.Builder buildBadRequestErrorMsg();
    OFFlowModFailedErrorMsg.Builder buildFlowModFailedErrorMsg();
    OFHelloFailedErrorMsg.Builder buildHelloFailedErrorMsg();
    OFPortModFailedErrorMsg.Builder buildPortModFailedErrorMsg();
    OFQueueOpFailedErrorMsg.Builder buildQueueOpFailedErrorMsg();
    OFBadInstructionErrorMsg.Builder buildBadInstructionErrorMsg() throws UnsupportedOperationException;
    OFBadMatchErrorMsg.Builder buildBadMatchErrorMsg() throws UnsupportedOperationException;
    OFGroupModFailedErrorMsg.Builder buildGroupModFailedErrorMsg() throws UnsupportedOperationException;
    OFSwitchConfigFailedErrorMsg.Builder buildSwitchConfigFailedErrorMsg() throws UnsupportedOperationException;
    OFTableModFailedErrorMsg.Builder buildTableModFailedErrorMsg() throws UnsupportedOperationException;
    OFRoleRequestFailedErrorMsg.Builder buildRoleRequestFailedErrorMsg() throws UnsupportedOperationException;
    OFBsnError.Builder buildBsnError() throws UnsupportedOperationException;
    OFMeterModFailedErrorMsg.Builder buildMeterModFailedErrorMsg() throws UnsupportedOperationException;
    OFTableFeaturesFailedErrorMsg.Builder buildTableFeaturesFailedErrorMsg() throws UnsupportedOperationException;
    OFAsyncConfigFailedErrorMsg.Builder buildAsyncConfigFailedErrorMsg() throws UnsupportedOperationException;
    OFBadPropertyErrorMsg.Builder buildBadPropertyErrorMsg() throws UnsupportedOperationException;
    OFBundleFailedErrorMsg.Builder buildBundleFailedErrorMsg() throws UnsupportedOperationException;
    OFFlowMonitorFailedErrorMsg.Builder buildFlowMonitorFailedErrorMsg() throws UnsupportedOperationException;

    OFMessageReader<OFErrorMsg> getReader();
    OFVersion getVersion();
}
